id = "pseudocode"
name = "PseudoCode"
version = "0.0.1"
schema_version = 1
authors = ["PseudoCodeInterpreter contributors"]
description = "PseudoCode language support."
repository = "https://github.com/mtmatt/PseudoCodeInterpreter"

[language_servers.pseudo-lsp]
name = "PseudoCode LSP"
languages = ["PseudoCode"]

[grammars.pseudocode]
repository = "https://github.com/mtmatt/tree-sitter-pseudocode"
rev = "6027e71677aa97846c1080044fdc09367185eb31"
